### ISSUE TITLE
Home Assistant integration?

### ISSUE THREAD

**Issue by josemabcn** [adrianmo/pymeteoclimatic#3]
Dear adrianno,

Do you plan to integrate Meteoclimatic in Home Assistant?.

Thanks

**Comment by adrianmo** [comment]
Hi @josemabcn, 

Absolutely, I'm also a Home Assistant user and I implemented the integration and submitted a PR a few months ago, shortly after releasing PyMeteoclimatic. However, the PR is still pending a second round of reviews and I don't know when it's going to get it. 

The PR link is this one: https://github.com/home-assistant/core/pull/36906

Please add a +1 reaction to the opening post in the PR to express your interest in the integration. 

Thank you!
