### ISSUE TITLE
Error 403 retrieving data

### ISSUE THREAD

**Issue by Bernhelm** [adrianmo/pymeteoclimatic#6]
Looks like Meteoclimatic API changed and stations requiere some kind of authorization. I'm getting 403 messages in all my stations:

"Error de configuración, se volverá a intentar: Error while retrieving data: Error fetching station data [status_code=403]"

Meteoclimatic web page plubished a post about "Alba" as their new API fully rewritten

**Comment by adrianmo** [comment]
Hey @Bernhelm, yes, unfortunately, it looks like Meteoclimatic has removed the old RSS feed we were using to obtain the station data. I'm trying to get access to the new API, but I haven't managed to get it yet. If anyone has a pointer or can shed some light, it'd be good. 

Let me also cross-link this issue to the one in the Home Assistant repo: https://github.com/home-assistant/core/issues/120591

**Comment by Bernhelm** [comment]
There is some info in https://www.meteoclimatic.com/es/doc/api

looks like new API requieres an apiKey parameter, but I'm unable to create an account

There is more info in their forum: https://forum.meteoclimatic.net/

**Comment by malvarezg** [comment]
It seems like to update station data owners obtain an apiKey from they private area. And as I've read in a post, without this apikey you cannot get data from the stations either.
I've tried to register but it hasn't worked for me either, i think that it is only aimed at station owners
I 've written an email to obtain some information about the future of the API

**Comment by adrianmo** [comment]
I'm closing this for now as Meteoclimatic has rolled back the old RSS feed that this library depends on.  The new APIs are not accessible at the moment, but let's keep an eye on it in case we can get preview access at some point and start to migrate the library to use them.  Thanks everyone that helped investigate and provide clarity! 💯
